language: php

php:
	-8.0.9

before_script:
	- travis_retry composer self_update
	- travis_retry composer update
	- travis_retry composer install --prefer-source --no-interaction
	- cp .env.example .env
	- php artisan key:generate

script:
	-vendor/bin/phpunit
